databases:
  - name: protracker
    databaseName: protracker
    user: protracker_user

services:
  - type: web
    name: protracker
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: protracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false