name: CI/CD

on:
  push:
    branches: [ main, development-1 ]
  pull_request:
    branches: [ main, development-1 ]

jobs:
  react:
    name: React
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd protracker-front
          npm install
      - name: Build
        run: |
          cd protracker-front
          npm run build
      - name: Test
        run: |
          cd protracker-front
          npm run test
  rails:
    name: Ruby on Rails
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd protracker-back
          bundle install
#       - name: Database setup and migration
#         run: |
#           cd protracker-back
#           bin/rails db:setup
#           if [ -f db/schema.rb ]; then
#             bin/rails db:migrate
#           fi
      - name: Test
        run: |
          cd protracker-back
          bin/rails test
